# Generated by Django 3.0.6 on 2020-05-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0002_testm'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetails',
        ),
    ]
