# Generated by Django 3.0.6 on 2020-05-28 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basics', '0003_delete_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
