# Generated by Django 3.0.6 on 2020-05-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200528_2140'),
        ('basics', '0004_contactm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(blank=True, default='Great Product!', null=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('item', models.ManyToManyField(to='core.Item')),
            ],
        ),
    ]
